=== HDFGroup/hdf5-json/h5json/schema/hdf5.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "$id": "https://hdfgroup.org/schemas/hdf5/json/hdf5.schema.json",
    "title": "HDF5 File JSON Schema",
    "description": "JSON Schema describing HDF5 file.",
    "type": "object",
    "required": [
        "apiVersion",
        "root"
    ],
    "properties": {
        "apiVersion": {
            "description": "HDF5/JSON version identifier.",
            "type": "string",
            "enum": [
                "1.0.0",
                "1.1.0",
                "1.1.1"
            ]
        },
        "id": {
            "description": "HDF5 file identifier.",
            "type": "string"
        },
        "root": {
            "description": "Unique identifier of the HDF5 root group.",
            "type": "string"
        },
        "created": {
            "description": "UTC date/time of file creation.",
            "type": "string",
            "format": "date-time"
        },
        "lastModified": {
            "description": "UTC date/time of last file content modification.",
            "type": "string",
            "format": "date-time"
        },
        "userblock": {
            "description": "HDF5 file user block.",
            "type": "array",
            "items": {
                "type": "integer"
            },
            "minItems": 1
        },
        "userblockSize": {
            "description": "HDF5 file user block size.",
            "type": "integer",
            "minimum": 512,
            "multipleOf": 2
        },
        "driverInfo": {
            "description": "HDF5 file driver information.",
            "oneOf": [
                {
                    "type": "object",
                    "properties": {
                        "memberSize": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        }
                    }
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "properties": {
                            "dataMap": {
                                "type": "string",
                                "enum": [
                                    "H5FD_MEM_SUPER",
                                    "H5FD_MEM_BTREE",
                                    "H5FD_MEM_DRAW",
                                    "H5FD_MEM_GHEAP",
                                    "H5FD_MEM_LHEAP",
                                    "H5FD_MEM_OHDR"
                                ]
                            },
                            "fileName": {
                                "type": "string"
                            },
                            "address": {
                                "type": "integer",
                                "exclusiveMinimum": 0
                            },
                            "relaxFlag": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "dataMap",
                            "fileName",
                            "address",
                            "relaxFlag"
                        ]
                    }
                }
            ]
        },
        "creationProperties": {
            "type": "object",
            "properties": {
                "chunkStorageConfig": {
                    "type": "object",
                    "properties": {
                        "chunkStorageBTreeHalfRank": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        }
                    },
                    "required": [
                        "chunkStorageBTreeHalfRank"
                    ]
                },
                "freeListConfig": {
                    "type": "object",
                    "properties": {
                        "freeListVersion": {
                            "type": "integer",
                            "minimum": 0
                        }
                    },
                    "required": [
                        "freeListVersion"
                    ]
                },
                "sizeConfig": {
                    "type": "object",
                    "properties": {
                        "lengthSizeInBytes": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "offsetSizeInBytes": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        }
                    },
                    "required": [
                        "lengthSizeInBytes",
                        "offsetSizeInBytes"
                    ]
                },
                "sohmConfig": {
                    "type": "object",
                    "properties": {
                        "maxList": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "minBTree": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "version": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "indexes": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "description": "HDF5 shared object header message (SOHM) index.",
                                "type": "object",
                                "properties": {
                                    "minMessageSize": {
                                        "type": "integer",
                                        "exclusiveMinimum": 0
                                    },
                                    "messageTypes": {
                                        "type": "array",
                                        "minItems": 1,
                                        "items": {
                                            "type": "string",
                                            "enum": [
                                                "H5O_SHMESG_ATTR_FLAG",
                                                "H5O_SHMESG_DTYPE_FLAG",
                                                "H5O_SHMESG_FILL_FLAG",
                                                "H5O_SHMESG_PLINE_FLAG",
                                                "H5O_SHMESG_SDSPACE_FLAG"
                                            ]
                                        }
                                    }
                                },
                                "required": [
                                    "minMessageSize",
                                    "messageTypes"
                                ]
                            }
                        }
                    },
                    "required": [
                        "maxList",
                        "minBTree",
                        "version",
                        "indexes"
                    ]
                },
                "superBlockVersion": {
                    "type": "integer",
                    "minimum": 0
                },
                "symbolTableConfig": {
                    "type": "object",
                    "properties": {
                        "nodeSize": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "treeRank": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "version": {
                            "type": "integer",
                            "minimum": 0
                        }
                    },
                    "required": [
                        "nodeSize",
                        "treeRank",
                        "version"
                    ]
                }
            }
        },
        "groups": {
            "description": "All groups in HDF5 file.",
            "type": "object",
            "$ref": "group.schema.json#/$defs/group"
        },
        "datasets": {
            "description": "All datasets in HDF5 file.",
            "type": "object",
            "$ref": "dataset.schema.json#/$defs/dataset"
        },
        "datatypes": {
            "description": "All committed datatypes in HDF5 file.",
            "type": "object",
            "$ref": "datatypes.schema.json#/$defs/committed"
        }
    }
}

=== HDFGroup/hdf5-json/data/json/null_objref_dset.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "79f6b0ae-4a9d-11e5-8d7b-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    1
                ]
            }, 
            "type": {
                "base": "H5T_STD_REF_OBJ", 
                "class": "H5T_REFERENCE"
            }, 
            "value": [
                "null"
            ]
        }
    }, 
    "groups": {
        "79f59b45-4a9d-11e5-a2d0-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "79f6b0ae-4a9d-11e5-8d7b-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "79f59b45-4a9d-11e5-a2d0-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/h5ex_d_alloc.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "77ffa578-4a9d-11e5-9dd9-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4, 
                    7
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    0, 
                    -1, 
                    -2, 
                    -3, 
                    -4, 
                    -5, 
                    -6
                ], 
                [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6
                ], 
                [
                    0, 
                    2, 
                    4, 
                    6, 
                    8, 
                    10, 
                    12
                ]
            ]
        }, 
        "77ffbbb3-4a9d-11e5-a650-3c15c2da029e": {
            "alias": [
                "/DS2"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_EARLY", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4, 
                    7
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    0, 
                    -1, 
                    -2, 
                    -3, 
                    -4, 
                    -5, 
                    -6
                ], 
                [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6
                ], 
                [
                    0, 
                    2, 
                    4, 
                    6, 
                    8, 
                    10, 
                    12
                ]
            ]
        }
    }, 
    "groups": {
        "77fe93c2-4a9d-11e5-8562-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "77ffa578-4a9d-11e5-9dd9-3c15c2da029e", 
                    "title": "DS1"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "77ffbbb3-4a9d-11e5-a650-3c15c2da029e", 
                    "title": "DS2"
                }
            ]
        }
    }, 
    "root": "77fe93c2-4a9d-11e5-8562-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/regionref_dset.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "a2b14a4c-83f8-11e5-82af-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    2
                ]
            }, 
            "type": {
                "base": "H5T_STD_REF_DSETREG", 
                "class": "H5T_REFERENCE"
            }, 
            "value": [
                {
                    "id": "a2b16111-83f8-11e5-9500-3c15c2da029e", 
                    "select_type": "H5S_SEL_POINTS", 
                    "selection": [
                        [
                            0, 
                            1
                        ], 
                        [
                            2, 
                            11
                        ], 
                        [
                            1, 
                            0
                        ], 
                        [
                            2, 
                            4
                        ]
                    ]
                }, 
                {
                    "id": "a2b16111-83f8-11e5-9500-3c15c2da029e", 
                    "select_type": "H5S_SEL_HYPERSLABS", 
                    "selection": [
                        [
                            [
                                0, 
                                0
                            ], 
                            [
                                1, 
                                3
                            ]
                        ], 
                        [
                            [
                                0, 
                                11
                            ], 
                            [
                                1, 
                                14
                            ]
                        ], 
                        [
                            [
                                2, 
                                0
                            ], 
                            [
                                3, 
                                3
                            ]
                        ], 
                        [
                            [
                                2, 
                                11
                            ], 
                            [
                                3, 
                                14
                            ]
                        ]
                    ]
                }
            ]
        }, 
        "a2b16111-83f8-11e5-9500-3c15c2da029e": {
            "alias": [
                "/DS2"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    3, 
                    16
                ]
            }, 
            "type": {
                "base": "H5T_STD_I8LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    84, 
                    104, 
                    101, 
                    32, 
                    113, 
                    117, 
                    105, 
                    99, 
                    107, 
                    32, 
                    98, 
                    114, 
                    111, 
                    119, 
                    110, 
                    0
                ], 
                [
                    102, 
                    111, 
                    120, 
                    32, 
                    106, 
                    117, 
                    109, 
                    112, 
                    115, 
                    32, 
                    111, 
                    118, 
                    101, 
                    114, 
                    32, 
                    0
                ], 
                [
                    116, 
                    104, 
                    101, 
                    32, 
                    53, 
                    32, 
                    108, 
                    97, 
                    122, 
                    121, 
                    32, 
                    100, 
                    111, 
                    103, 
                    115, 
                    0
                ]
            ]
        }
    }, 
    "groups": {
        "a2b01eb3-83f8-11e5-9199-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "a2b14a4c-83f8-11e5-82af-3c15c2da029e", 
                    "title": "DS1"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "a2b16111-83f8-11e5-9500-3c15c2da029e", 
                    "title": "DS2"
                }
            ]
        }
    }, 
    "root": "a2b01eb3-83f8-11e5-9199-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/opaque_dset.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "7a8e3535-4a9d-11e5-857d-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4
                ]
            }, 
            "type": {
                "class": "H5T_OPAQUE", 
                "size": 7
            }, 
            "value": "????"
        }
    }, 
    "groups": {
        "7a8ccecf-4a9d-11e5-9da0-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "7a8e3535-4a9d-11e5-857d-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "7a8ccecf-4a9d-11e5-9da0-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/null_space_dset.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "7a27e93d-4a9d-11e5-ba75-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_NULL"
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": null
        }
    }, 
    "groups": {
        "7a26da87-4a9d-11e5-a55e-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "7a27e93d-4a9d-11e5-ba75-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "7a26da87-4a9d-11e5-a55e-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/committed_type.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "c8bd52c7-5dc4-11e5-9885-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": [
                    0, 
                    "", 
                    0.0, 
                    0.0
                ], 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4
                ]
            }, 
            "type": "datatypes/c8bd6970-5dc4-11e5-913e-3c15c2da029e", 
            "value": [
                [
                    12345678, 
                    "SEA", 
                    56.3, 
                    29.35
                ], 
                [
                    12333343, 
                    "LAX", 
                    73.3, 
                    32.33
                ], 
                [
                    14543645, 
                    "PDX", 
                    65.3, 
                    31.23
                ], 
                [
                    14344545, 
                    "IDA", 
                    72.3, 
                    30.43
                ]
            ]
        }
    }, 
    "datatypes": {
        "c8bd6970-5dc4-11e5-913e-3c15c2da029e": {
            "alias": [
                "/Sensor_Type"
            ], 
            "type": {
                "class": "H5T_COMPOUND", 
                "fields": [
                    {
                        "name": "Serial number", 
                        "type": {
                            "base": "H5T_STD_I64BE", 
                            "class": "H5T_INTEGER"
                        }
                    }, 
                    {
                        "name": "Location", 
                        "type": {
                            "charSet": "H5T_CSET_ASCII", 
                            "class": "H5T_STRING", 
                            "length": 3, 
                            "strPad": "H5T_STR_NULLPAD"
                        }
                    }, 
                    {
                        "name": "Temperature (F)", 
                        "type": {
                            "base": "H5T_IEEE_F64BE", 
                            "class": "H5T_FLOAT"
                        }
                    }, 
                    {
                        "name": "Pressure (inHg)", 
                        "type": {
                            "base": "H5T_IEEE_F64BE", 
                            "class": "H5T_FLOAT"
                        }
                    }
                ]
            }
        }
    }, 
    "groups": {
        "c8bbf0a3-5dc4-11e5-bfdb-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "attributes": [
                {
                    "name": "attr1", 
                    "shape": {
                        "class": "H5S_SCALAR"
                    }, 
                    "type": "datatypes/c8bd6970-5dc4-11e5-913e-3c15c2da029e", 
                    "value": [
                        0, 
                        "0", 
                        0.0, 
                        0.0
                    ]
                }
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "c8bd52c7-5dc4-11e5-9885-3c15c2da029e", 
                    "title": "DS1"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datatypes", 
                    "id": "c8bd6970-5dc4-11e5-913e-3c15c2da029e", 
                    "title": "Sensor_Type"
                }
            ]
        }
    }, 
    "root": "c8bbf0a3-5dc4-11e5-bfdb-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/objref_dset.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "7a59a375-4a9d-11e5-8504-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    2
                ]
            }, 
            "type": {
                "base": "H5T_STD_REF_OBJ", 
                "class": "H5T_REFERENCE"
            }, 
            "value": [
                "groups/7a59cc17-4a9d-11e5-aaa9-3c15c2da029e", 
                "datasets/7a59ba17-4a9d-11e5-9c81-3c15c2da029e"
            ]
        }, 
        "7a59ba17-4a9d-11e5-9c81-3c15c2da029e": {
            "alias": [
                "/DS2"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_NULL"
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": null
        }
    }, 
    "groups": {
        "7a58889c-4a9d-11e5-86cb-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "7a59a375-4a9d-11e5-8504-3c15c2da029e", 
                    "title": "DS1"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "7a59ba17-4a9d-11e5-9c81-3c15c2da029e", 
                    "title": "DS2"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "groups", 
                    "id": "7a59cc17-4a9d-11e5-aaa9-3c15c2da029e", 
                    "title": "G1"
                }
            ]
        }, 
        "7a59cc17-4a9d-11e5-aaa9-3c15c2da029e": {
            "alias": [
                "/G1"
            ]
        }
    }, 
    "root": "7a58889c-4a9d-11e5-86cb-3c15c2da029e"
}
