=== HDFGroup/hdf5-json/h5json/schema/hdf5.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "$id": "https://hdfgroup.org/schemas/hdf5/json/hdf5.schema.json",
    "title": "HDF5 File JSON Schema",
    "description": "JSON Schema describing HDF5 file.",
    "type": "object",
    "required": [
        "apiVersion",
        "root"
    ],
    "properties": {
        "apiVersion": {
            "description": "HDF5/JSON version identifier.",
            "type": "string",
            "enum": [
                "1.0.0",
                "1.1.0",
                "1.1.1"
            ]
        },
        "id": {
            "description": "HDF5 file identifier.",
            "type": "string"
        },
        "root": {
            "description": "Unique identifier of the HDF5 root group.",
            "type": "string"
        },
        "created": {
            "description": "UTC date/time of file creation.",
            "type": "string",
            "format": "date-time"
        },
        "lastModified": {
            "description": "UTC date/time of last file content modification.",
            "type": "string",
            "format": "date-time"
        },
        "userblock": {
            "description": "HDF5 file user block.",
            "type": "array",
            "items": {
                "type": "integer"
            },
            "minItems": 1
        },
        "userblockSize": {
            "description": "HDF5 file user block size.",
            "type": "integer",
            "minimum": 512,
            "multipleOf": 2
        },
        "driverInfo": {
            "description": "HDF5 file driver information.",
            "oneOf": [
                {
                    "type": "object",
                    "properties": {
                        "memberSize": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        }
                    }
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "properties": {
                            "dataMap": {
                                "type": "string",
                                "enum": [
                                    "H5FD_MEM_SUPER",
                                    "H5FD_MEM_BTREE",
                                    "H5FD_MEM_DRAW",
                                    "H5FD_MEM_GHEAP",
                                    "H5FD_MEM_LHEAP",
                                    "H5FD_MEM_OHDR"
                                ]
                            },
                            "fileName": {
                                "type": "string"
                            },
                            "address": {
                                "type": "integer",
                                "exclusiveMinimum": 0
                            },
                            "relaxFlag": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "dataMap",
                            "fileName",
                            "address",
                            "relaxFlag"
                        ]
                    }
                }
            ]
        },
        "creationProperties": {
            "type": "object",
            "properties": {
                "chunkStorageConfig": {
                    "type": "object",
                    "properties": {
                        "chunkStorageBTreeHalfRank": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        }
                    },
                    "required": [
                        "chunkStorageBTreeHalfRank"
                    ]
                },
                "freeListConfig": {
                    "type": "object",
                    "properties": {
                        "freeListVersion": {
                            "type": "integer",
                            "minimum": 0
                        }
                    },
                    "required": [
                        "freeListVersion"
                    ]
                },
                "sizeConfig": {
                    "type": "object",
                    "properties": {
                        "lengthSizeInBytes": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "offsetSizeInBytes": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        }
                    },
                    "required": [
                        "lengthSizeInBytes",
                        "offsetSizeInBytes"
                    ]
                },
                "sohmConfig": {
                    "type": "object",
                    "properties": {
                        "maxList": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "minBTree": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "version": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "indexes": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "description": "HDF5 shared object header message (SOHM) index.",
                                "type": "object",
                                "properties": {
                                    "minMessageSize": {
                                        "type": "integer",
                                        "exclusiveMinimum": 0
                                    },
                                    "messageTypes": {
                                        "type": "array",
                                        "minItems": 1,
                                        "items": {
                                            "type": "string",
                                            "enum": [
                                                "H5O_SHMESG_ATTR_FLAG",
                                                "H5O_SHMESG_DTYPE_FLAG",
                                                "H5O_SHMESG_FILL_FLAG",
                                                "H5O_SHMESG_PLINE_FLAG",
                                                "H5O_SHMESG_SDSPACE_FLAG"
                                            ]
                                        }
                                    }
                                },
                                "required": [
                                    "minMessageSize",
                                    "messageTypes"
                                ]
                            }
                        }
                    },
                    "required": [
                        "maxList",
                        "minBTree",
                        "version",
                        "indexes"
                    ]
                },
                "superBlockVersion": {
                    "type": "integer",
                    "minimum": 0
                },
                "symbolTableConfig": {
                    "type": "object",
                    "properties": {
                        "nodeSize": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "treeRank": {
                            "type": "integer",
                            "exclusiveMinimum": 0
                        },
                        "version": {
                            "type": "integer",
                            "minimum": 0
                        }
                    },
                    "required": [
                        "nodeSize",
                        "treeRank",
                        "version"
                    ]
                }
            }
        },
        "groups": {
            "description": "All groups in HDF5 file.",
            "type": "object",
            "$ref": "group.schema.json#/$defs/group"
        },
        "datasets": {
            "description": "All datasets in HDF5 file.",
            "type": "object",
            "$ref": "dataset.schema.json#/$defs/dataset"
        },
        "datatypes": {
            "description": "All committed datatypes in HDF5 file.",
            "type": "object",
            "$ref": "datatypes.schema.json#/$defs/committed"
        }
    }
}

=== HDFGroup/hdf5-json/data/json/array_dset.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "613344d9-4a9d-11e5-8ca2-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": [
                    [
                        0, 
                        0, 
                        4301258764, 
                        0, 
                        0
                    ], 
                    [
                        0, 
                        0, 
                        0, 
                        0, 
                        -5803105942641292133
                    ], 
                    [
                        4301365008, 
                        4297860608, 
                        7012041387394527100, 
                        4301375792, 
                        4347480760
                    ]
                ], 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4
                ]
            }, 
            "type": {
                "base": {
                    "base": "H5T_STD_I64LE", 
                    "class": "H5T_INTEGER"
                }, 
                "class": "H5T_ARRAY", 
                "dims": [
                    3, 
                    5
                ]
            }, 
            "value": [
                [
                    [
                        0, 
                        0, 
                        0, 
                        0, 
                        0
                    ], 
                    [
                        0, 
                        -1, 
                        -2, 
                        -3, 
                        -4
                    ], 
                    [
                        0, 
                        -2, 
                        -4, 
                        -6, 
                        -8
                    ]
                ], 
                [
                    [
                        0, 
                        1, 
                        2, 
                        3, 
                        4
                    ], 
                    [
                        1, 
                        1, 
                        1, 
                        1, 
                        1
                    ], 
                    [
                        2, 
                        1, 
                        0, 
                        -1, 
                        -2
                    ]
                ], 
                [
                    [
                        0, 
                        2, 
                        4, 
                        6, 
                        8
                    ], 
                    [
                        2, 
                        3, 
                        4, 
                        5, 
                        6
                    ], 
                    [
                        4, 
                        4, 
                        4, 
                        4, 
                        4
                    ]
                ], 
                [
                    [
                        0, 
                        3, 
                        6, 
                        9, 
                        12
                    ], 
                    [
                        3, 
                        5, 
                        7, 
                        9, 
                        11
                    ], 
                    [
                        6, 
                        7, 
                        8, 
                        9, 
                        10
                    ]
                ]
            ]
        }
    }, 
    "groups": {
        "6131fede-4a9d-11e5-b721-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "613344d9-4a9d-11e5-8ca2-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "6131fede-4a9d-11e5-b721-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/dset_creationprop.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "9c1f15c7-83f8-11e5-8870-3c15c2da029e": {
            "alias": [
                "/dset1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    10
                ]
            }, 
            "type": {
                "base": "H5T_IEEE_F32LE", 
                "class": "H5T_FLOAT"
            }, 
            "value": [
                0.0, 
                0.0, 
                0.0, 
                0.0, 
                0.0, 
                0.0, 
                0.0, 
                0.0, 
                0.0, 
                0.0
            ]
        }
    }, 
    "groups": {
        "9c1d7c8c-83f8-11e5-af5e-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "9c1f15c7-83f8-11e5-8870-3c15c2da029e", 
                    "title": "dset1"
                }
            ]
        }
    }, 
    "root": "9c1d7c8c-83f8-11e5-af5e-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/h5ex_d_chunk.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "783150a1-4a9d-11e5-a43e-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_INCR", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CHUNKED", 
                    "dims": [
                        4, 
                        4
                    ]
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    6, 
                    8
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    0, 
                    1, 
                    0, 
                    0, 
                    1, 
                    0, 
                    0, 
                    1
                ], 
                [
                    1, 
                    1, 
                    0, 
                    1, 
                    1, 
                    0, 
                    1, 
                    1
                ], 
                [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ], 
                [
                    0, 
                    1, 
                    0, 
                    0, 
                    1, 
                    0, 
                    0, 
                    1
                ], 
                [
                    1, 
                    1, 
                    0, 
                    1, 
                    1, 
                    0, 
                    1, 
                    1
                ], 
                [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ]
            ]
        }
    }, 
    "groups": {
        "782fd4b3-4a9d-11e5-918d-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "783150a1-4a9d-11e5-a43e-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "782fd4b3-4a9d-11e5-918d-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/h5ex_d_unlimadd.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "77398d23-4c30-11e5-97ba-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_INCR", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CHUNKED", 
                    "dims": [
                        4, 
                        4
                    ]
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    6, 
                    10
                ], 
                "maxdims": [
                    "H5S_UNLIMITED", 
                    "H5S_UNLIMITED"
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    0, 
                    -1, 
                    -2, 
                    -3, 
                    -4, 
                    -5, 
                    -6, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    2, 
                    4, 
                    6, 
                    8, 
                    10, 
                    12, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7, 
                    8, 
                    9
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6, 
                    7, 
                    8, 
                    9
                ]
            ]
        }
    }, 
    "groups": {
        "7738798c-4c30-11e5-9838-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "77398d23-4c30-11e5-97ba-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "7738798c-4c30-11e5-9838-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/h5ex_d_rdwr.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "78e1b405-4a9d-11e5-80b8-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4, 
                    7
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    0, 
                    -1, 
                    -2, 
                    -3, 
                    -4, 
                    -5, 
                    -6
                ], 
                [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6
                ], 
                [
                    0, 
                    2, 
                    4, 
                    6, 
                    8, 
                    10, 
                    12
                ]
            ]
        }
    }, 
    "groups": {
        "78e08e6b-4a9d-11e5-8191-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "78e1b405-4a9d-11e5-80b8-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "78e08e6b-4a9d-11e5-8191-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/namedtype.json
{
    "apiVersion": "1.0.0", 
    "datatypes": {
        "79c561de-4a9d-11e5-a5c8-3c15c2da029e": {
            "alias": [
                "/dtype_compound"
            ], 
            "type": {
                "class": "H5T_COMPOUND", 
                "fields": [
                    {
                        "name": "temp", 
                        "type": {
                            "base": "H5T_STD_I32LE", 
                            "class": "H5T_INTEGER"
                        }
                    }, 
                    {
                        "name": "pressure", 
                        "type": {
                            "base": "H5T_IEEE_F32LE", 
                            "class": "H5T_FLOAT"
                        }
                    }
                ]
            }
        }, 
        "79c5769c-4a9d-11e5-950e-3c15c2da029e": {
            "alias": [
                "/dtype_simple"
            ], 
            "attributes": [
                {
                    "name": "note", 
                    "shape": {
                        "class": "H5S_SCALAR"
                    }, 
                    "type": {
                        "charSet": "H5T_CSET_ASCII", 
                        "class": "H5T_STRING", 
                        "length": "H5T_VARIABLE", 
                        "strPad": "H5T_STR_NULLTERM"
                    }, 
                    "value": "this is a committed datatype of float32"
                }
            ], 
            "type": {
                "base": "H5T_IEEE_F32LE", 
                "class": "H5T_FLOAT"
            }
        }
    }, 
    "groups": {
        "79c44830-4a9d-11e5-9b42-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datatypes", 
                    "id": "79c561de-4a9d-11e5-a5c8-3c15c2da029e", 
                    "title": "dtype_compound"
                }, 
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datatypes", 
                    "id": "79c5769c-4a9d-11e5-950e-3c15c2da029e", 
                    "title": "dtype_simple"
                }
            ]
        }
    }, 
    "root": "79c44830-4a9d-11e5-9b42-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/vlen_string_attr.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "847bbfc7-4a9d-11e5-be47-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "attributes": [
                {
                    "name": "A1", 
                    "shape": {
                        "class": "H5S_SIMPLE", 
                        "dims": [
                            4
                        ]
                    }, 
                    "type": {
                        "charSet": "H5T_CSET_ASCII", 
                        "class": "H5T_STRING", 
                        "length": "H5T_VARIABLE", 
                        "strPad": "H5T_STR_NULLTERM"
                    }, 
                    "value": [
                        "Parting", 
                        "is such", 
                        "sweet", 
                        "sorrow."
                    ]
                }
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_LATE", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_CONTIGUOUS"
                }
            }, 
            "shape": {
                "class": "H5S_NULL"
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": null
        }
    }, 
    "groups": {
        "847a8963-4a9d-11e5-b169-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "847bbfc7-4a9d-11e5-be47-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "847a8963-4a9d-11e5-b169-3c15c2da029e"
}

=== HDFGroup/hdf5-json/data/json/h5ex_d_compact.json
{
    "apiVersion": "1.0.0", 
    "datasets": {
        "784aedcf-4a9d-11e5-982b-3c15c2da029e": {
            "alias": [
                "/DS1"
            ], 
            "creationProperties": {
                "allocTime": "H5D_ALLOC_TIME_EARLY", 
                "fillTime": "H5D_FILL_TIME_IFSET", 
                "fillValue": 0, 
                "layout": {
                    "class": "H5D_COMPACT"
                }
            }, 
            "shape": {
                "class": "H5S_SIMPLE", 
                "dims": [
                    4, 
                    7
                ]
            }, 
            "type": {
                "base": "H5T_STD_I32LE", 
                "class": "H5T_INTEGER"
            }, 
            "value": [
                [
                    0, 
                    -1, 
                    -2, 
                    -3, 
                    -4, 
                    -5, 
                    -6
                ], 
                [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ], 
                [
                    0, 
                    1, 
                    2, 
                    3, 
                    4, 
                    5, 
                    6
                ], 
                [
                    0, 
                    2, 
                    4, 
                    6, 
                    8, 
                    10, 
                    12
                ]
            ]
        }
    }, 
    "groups": {
        "7849a93d-4a9d-11e5-8fb4-3c15c2da029e": {
            "alias": [
                "/"
            ], 
            "links": [
                {
                    "class": "H5L_TYPE_HARD", 
                    "collection": "datasets", 
                    "id": "784aedcf-4a9d-11e5-982b-3c15c2da029e", 
                    "title": "DS1"
                }
            ]
        }
    }, 
    "root": "7849a93d-4a9d-11e5-8fb4-3c15c2da029e"
}
